name: Leandro Oriente
markdown: redcarpet
pygments: true
permalink: /:title
paginate: 5

title : Leandro Oriente
tagline: Desenvolvedor Front End
author :
  name : Leandro Oriente
  email : leandroriente@gmail.com
  github : leandrooriente
  facebook : http://facebook.com/leandrooriente
  googleplus : https://plus.google.com/100466667846971992298?rel=author
  500px : http://500px.com/leandrooriente
  linkedin : http://www.linkedin.com/in/leandrooriente
  instagram : http://instagram.com/leandrooriente

production_url : http://leandrooriente.com

theme :
  comments :
    provider : disqus
    disqus :
      short_name : leandrooriente

analytics :
    provider : google 
    google : 
        tracking_id : 'UA-25340215-1'