# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Leandro Oriente
subtitle: Desenvolvedor Front End
description:
author: Leandro Oriente
theme: oriente-theme

logo:
  title: Oriente
  subtitle: Desenvolvedor Front End

url: https://leandrooriente.com
root: /

# SEO
permalink: :title/
sitemap:
  path: sitemap.xml

social:
  linkedin: https://www.linkedin.com/in/leandrooriente
  github: https://github.com/leandrooriente/
  rss: /atom.xml

fb_app: 235902153193497

# Directory
source_dir: source
public_dir: public
code_dir: downloads/code

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
timezone: America/Sao_Paulo
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

date_format: DD/MM/YYYY
time_format: HH:mm:ss

disqus_shortname: leandrooriente

# Pagination

per_page: 20
pagination_dir: page

# Deploy
feed:
  type: atom
  path: atom.xml
  limit: 0

html_minifier:
  removeComments: true
  collapseWhitespace: true
  removeScriptTypeAttributes: true
  removeStyleLinkTypeAttributes: true

deploy:
  type: git
  repo: git@github.com:leandrooriente/leandrooriente.git
  branch: dist
  message: Deploy
  name: leandrooriente
  email: leandroriente@gmail.com
